providers = ["python"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
nixPkgs = ["pandoc"]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port 5050"