providers = ["python"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port 5050"